/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ex006;

/**
 *
 * @author franz
 */
public class RadioGUI extends javax.swing.JFrame {

    /**
     * Creates new form RadioGUI
     */
    public RadioGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jmHinzu = new javax.swing.JMenuItem();
        jmBandverst = new javax.swing.JMenuItem();
        jmBandanz = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();

        jmHinzu.setText("hinzufügen");
        jmHinzu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onHinzufuegen(evt);
            }
        });
        jPopupMenu1.add(jmHinzu);

        jmBandverst.setText("Band verstecken");
        jmBandverst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onBandVerstecken(evt);
            }
        });
        jPopupMenu1.add(jmBandverst);

        jmBandanz.setText("Band anzeigen");
        jmBandanz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onBandAnzeigen(evt);
            }
        });
        jPopupMenu1.add(jmBandanz);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout());

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table.setColumnSelectionAllowed(true);
        table.setComponentPopupMenu(jPopupMenu1);
        jScrollPane1.setViewportView(table);

        getContentPane().add(jScrollPane1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void onHinzufuegen(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onHinzufuegen
        // TODO add your handling code here:
    }//GEN-LAST:event_onHinzufuegen

    private void onBandVerstecken(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onBandVerstecken
        // TODO add your handling code here:
    }//GEN-LAST:event_onBandVerstecken

    private void onBandAnzeigen(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onBandAnzeigen
        // TODO add your handling code here:
    }//GEN-LAST:event_onBandAnzeigen

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RadioGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RadioGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RadioGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RadioGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RadioGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem jmBandanz;
    private javax.swing.JMenuItem jmBandverst;
    private javax.swing.JMenuItem jmHinzu;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
